# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "MyApp"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# Configurar el motor de manejo de sesiones

session: "simple"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "tiny"

# Configurar el plugin de conexion con la base de datos

plugins:
    Database:
        driver: 'mysql'
        database: 'mydb'
        username: 'prueba'
        password: 'prueba'

    ValidateTiny:
        rules_dir: lib/validacion
        error_prefix: err_
        is_full: 0


